---
- name: tags demo
  hosts: client
  tasks:
   - yum:
      name: httpd
      state: absent
     tags:
      - tag1
   - service:
      name: httpd
      state: started
     tags:
      - serve
   - debug:
      msg: tags demo
     tags:
      - always
